services:
  syntheditor:
    build:
      context: ./syntheditor
    ports:
      - 3000:3000
    volumes:
      - ./syntheditor:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
networks:
  default:
    name: syntheditor-network
