services:
  syntheditor:
    build:
      context: syntheditor
    ports:
      - 3000:3000
    volumes:
      - ./syntheditor:/syntheditor
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
