// app/layout.tsx
import type { Metadata } from 'next';
import { BLEProvider } from '@/providers/ble-provider';
import { MeshProvider } from '@/providers/mesh-provider';
import { DeviceTypeProvider } from '@/providers/device-type-provider';
import { CommandProvider } from '@/providers/command-provider';
import { AppStateProvider } from '@/providers/appstate-provider';

export const metadata: Metadata = {
    title: 'My App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ja">
            <body>
                <BLEProvider>
                    <MeshProvider>
                        <DeviceTypeProvider>
                            <CommandProvider>
                                <AppStateProvider>
                                    {children}
                                </AppStateProvider>
                            </CommandProvider>
                        </DeviceTypeProvider>
                    </MeshProvider>
                </BLEProvider>
            </body>
        </html>
    );
}