export const APPSTATE_ID_PLAYER = 0x10;
export const APPSTATE_ID_PLAYER_QUANTIZER = APPSTATE_ID_PLAYER + 0x01;
export const APPSTATE_ID_PLAYER_METRONOME = APPSTATE_ID_PLAYER + 0x02;
export const APPSTATE_ID_PLAYER_RECORDER = APPSTATE_ID_PLAYER + 0x03;
export const APPSTATE_ID_PLAYER_TICK_CLOCK = APPSTATE_ID_PLAYER + 0x04;
export const APPSTATE_ID_PLAYER_CURRENT_TRACKS = APPSTATE_ID_PLAYER + 0x05;
export const APPSTATE_ID_PLAYER_DEVICE_POSITIONS = APPSTATE_ID_PLAYER + 0x06;
export const APPSTATE_ID_PLAYER_TRACK_STATES = APPSTATE_ID_PLAYER + 0x07;
