export const COMMAND_CLIENT_ID_APPSTATE_RETRIEVE = 0x06;
export const COMMAND_CLIENT_ID_APPSTATE_NOTIFY = 0x07;
export const COMMAND_CLIENT_ID_PLAYER_CONTROL = 0x08;

export const COMMAND_CLIENT_ID_DATA_TRANSFER = 0x09;