export const COMMAND_CLIENT_ID_APPSTATE_RETRIEVE = 0x06;
export const COMMAND_CLIENT_ID_APPSTATE_NOTIFY = 0x07;
export const COMMAND_CLIENT_ID_DEVICE_CONTROL = 0x08;

export const COMMAND_CLIENT_ID_DATA_TRANSFER = 0x09;
export const COMMAND_CLIENT_ID_EDITOR_SETTINGS_CONFIG = 0x0A;
// CRDT-related client IDs (device parity)
export const COMMAND_CLIENT_ID_CRDT_HASH_AUDIT = 0x0B;
export const COMMAND_CLIENT_ID_CRDT_SEQUENCE = 0x0C;
export const COMMAND_CLIENT_ID_CRDT_FULL_STATE = 0x0D;